 const products = [
  {
    id: 1,
    name: "iPhone 16",
    category: "Mobiles",
    brand: "Apple",
    price: 85000,
    stock: 15,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Galaxy S25",
    category: "Mobiles",
    brand: "Samsung",
    price: 76000,
    stock: 20,
    rating: 4.7,
  },
  {
    id: 3,
    name: "MacBook Air M4",
    category: "Laptops",
    brand: "Apple",
    price: 125000,
    stock: 8,
    rating: 4.9,
  },
  {
    id: 4,
    name: "Dell XPS 15",
    category: "Laptops",
    brand: "Dell",
    price: 118000,
    stock: 10,
    rating: 4.6,
  },
  {
    id: 5,
    name: "Sony WH-1000XM6",
    category: "Headphones",
    brand: "Sony",
    price: 29999,
    stock: 25,
    rating: 4.8,
  },
  {
    id: 6,
    name: "iPad Air",
    category: "Tablets",
    brand: "Apple",
    price: 64999,
    stock: 12,
    rating: 4.7,
  },
  {
    id: 7,
    name: "Boat Rockerz 550",
    category: "Headphones",
    brand: "Boat",
    price: 1999,
    stock: 50,
    rating: 4.2,
  },
  {
    id: 8,
    name: "Nothing Phone 3",
    category: "Mobiles",
    brand: "Nothing",
    price: 42999,
    stock: 18,
    rating: 4.5,
  },
];

module.exports = products;